### PR TITLE
fix: remove /MD from cmake config

### PR DESCRIPTION
**Pull request by SchrodingerZhu**

### CODE REVIEW

**Comment by SchrodingerZhu** [comment]
fix #104

**Review by mjp41 — APPROVED** [review]
LGTM, as long as it does what the docs say, but I am sure CI will break if it doesn't.

**Comment by SchrodingerZhu** [comment]
@mjp41 sadly, the travis ci in this repo has run out its quota. I am installing a VM to test it out. not very familiar with MSVC thou.

**Comment by mjp41** [comment]
Github actions or Azure Pipelines would give unlimited CI for a "public" project.

**Comment by SchrodingerZhu** [comment]
so I ran the test, unfortunately it stills has some errors due to undefined symbols:
```
__imp_puts
``` 
This seems like sth from a DLL?

**Comment by SchrodingerZhu** [comment]
I think current configuration actually did not consider the static linking:
```
    if cfg!(all(windows, target_env = "msvc")) {
        println!("cargo:rustc-link-lib=dylib=mincore");
        println!("cargo:rustc-link-search=native={}/{}", dst.display(), build_type);
    } else {
        println!("cargo:rustc-link-search=native={}", dst.display());
    }

    if cfg!(all(windows, target_env = "gnu")) {
        let stdout = std::process::Command::new("gcc")
            .args(&["-print-search-dirs"])
            .output().unwrap_or_else(|_| {
            eprintln!("Cannot run gcc.exe");
            std::process::abort();
        })
            .stdout;

        let outputs = String::from_utf8(stdout)
            .unwrap_or_else(|_| {
                eprintln!("gcc output contains non-utf8 characters");
                std::process::abort();
            });

        outputs.lines()
            .filter(|line| line.starts_with("libraries: ="))
            .map(|line| line.split_at("libraries: =".len()).1)
            .flat_map(|line| line.split(";"))
            .for_each(|path| {
                println!("cargo:rustc-link-search=native={}", path);
            });

        println!("cargo:rustc-link-lib=dylib=stdc++");
        println!("cargo:rustc-link-lib=dylib=atomic");
        println!("cargo:rustc-link-lib=dylib=winpthread");
        println!("cargo:rustc-link-lib=dylib=gcc_s");
    }
```
so for msvc and gnu (which is not actually supported), we all use dynamic libs; this may be troublesome with using static c runtime.

**Comment by SchrodingerZhu** [comment]
sorry for the noise. I forgot to switch the branch before the test.... it is fixed.

**Pull request merged**
