### PR TITLE
No dylib des

### PR DESCRIPTION
**Pull request by ryancinsight**
removal of dylib

### CODE REVIEW

**Comment by ryancinsight** [comment]
Interesting lto does not work for cc or gcc on x86_64

**Comment by ryancinsight** [comment]
@mjp41 any ideas why cmake lto flag fails on msvc, ubuntu cc compiler with file format not recognized errors?

**Comment by ryancinsight** [comment]
> @mjp41 any ideas why cmake lto flag fails on msvc, ubuntu cc compiler with file format not recognized errors?

Have a feeling I need println!("cargo::rustc-flags=-Clinker-plugin-lto"); I'll test later today

**Comment by mjp41** [comment]
Sorry, this is not my area of expertise.  I can try and investigate on a Windows machine if you get stuck.

**Comment by ryancinsight** [comment]
> Sorry, this is not my area of expertise. I can try and investigate on a Windows machine if you get stuck.

seems it may be related to IPO and VS studio, Ill have to submit a snmalloc adjustment to cmakelist

**Pull request closed without merging**
