### PR TITLE
Snmalloc 2

### PR DESCRIPTION
**Pull request by SchrodingerZhu**

### CODE REVIEW

**Comment by SchrodingerZhu** [comment]
@mjp41 local build passed.

**Comment by mjp41** [comment]
Looks like it can't find `atexit`, which we use to remove the `libstc++` requirement.  Which `C` runtime is being linked in?

Alternatively, using `-DSNMALLOC_CLEANUP=CXX11_DESTRUCTORS` will not use `atexit`.  But requires the C++ runtime to be linked.

**Comment by SchrodingerZhu** [comment]
what happened to github actions

**Comment by SchrodingerZhu** [comment]
I cannot reproduce the error for ubuntu at my local minimal 20.04 docker.

**Comment by SchrodingerZhu** [comment]
@mjp41 ubuntu really package libc badly...

**Pull request merged**
