### PR TITLE
fix mingw

### PR DESCRIPTION
**Pull request by SchrodingerZhu**

### CODE REVIEW

**Comment by mjp41** [comment]
Mingw is still failing, can't find -latomic.  But the error is now silenced.

**Comment by SchrodingerZhu** [comment]
It actually works on my local machine.

**Comment by SchrodingerZhu** [comment]
conclusion: integrate c++ with rust on MinGW is a nightmare.

**Comment by SchrodingerZhu** [comment]
The current solution is too ugly. @ice1000, @iceyself, do you have any suggestions?

**Comment by ICEYSELF** [comment]
> The current solution is too ugly.

As far as I know, the `clang` compiler uses a more ugly way to detect GCC, and even itself. It tries a lot of combinations of paths. Life will be simpler without these programs.

**Comment by ICEYSELF** [comment]
If a `gcc.exe` is in path, we can use the Windows `where.exe` to find out its path, and try several combinations with that path.

**Comment by SchrodingerZhu** [comment]
@ICEYSELF MinGW has all libraries, either in its `bin` or in its `lib/gcc/ARGCH/VERSION`, cmake detects everything smoothly but rust does not.
More strangely, sometimes cargo cannot find winpthread library and sometimes it can. Both `winpthread` and `atomic` adapts `lib<name>-<version>.dll` format, but rust only recognize `atomic-1` rather than `atomic`. 
Also, it is possible that these dlls are not in PATH, so I also tried static linking. MinGW gcc has `-static-gcc -static-stdc++` but it does not has something like `-static-atomic`. ATOMIC is a part of STL, RIGHT? All these things are bringing MinGW support into a total chaos.

**Comment by SchrodingerZhu** [comment]
Is it possible to dump some useful info from `cmake`?

**Comment by ice1000** [comment]
> Is it possible to dump some useful info from `cmake`?

If you specify the generator, you can dump 'em from `CMakeFiles`

**Comment by SchrodingerZhu** [comment]
going to merge this anyway. will keep the issue open and current stage will be stated in the issue.

**Pull request merged**
